#!/bin/sh

# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then change the above line to refer to that shell.
#
#   (2) All environment variables ending with _OPTS are used as additional
#       command options for the JVM hosting the Gradle process.
#       See also https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_environment_variables
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
# Discard cd standard output in case $CDPATH is set (https://github.com/gradle/gradle/issues/25036)
APP_HOME=$( cd "${APP_HOME:-./}" > /dev/null && pwd -P ) || exit

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;;
esac

# For Cygwin or MSYS2, switch paths to Windows format before running java
if $cygwin || $msys ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg do
        if
            case $arg in                                #(
              -*)   false ;;                           # don't mess with options #(
              /?*)  true ;;                            # could be absolute path #((
              *)    false ;;
            esac
        then
            arg=$( cygpath --path --mixed "$arg" )
        fi
        # Roll the args list around by copying all entries except the first
        args=$( printf '%s\n' $args ; printf '%s\n' "$arg" )
    done

    # Then put the rolled-back args list into $@
    set -- $args
    [ -n "$args" ] || set -- # $@ is empty
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args of this script
#   * ADD_OPTS
#   * default JVM options
#   * main-klass
#   * -classpath
#   * CLASSPATH
#   * -Dapp.name
#   * -Dapp.home
#   * -Dorg.gradle.appname
set -- \
        -Dorg.gradle.appname="$APP_BASE_NAME" \
        -Dapp.home="$APP_HOME" \
        -Dapp.name="$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Stop when "xargs" is not available.
command -v xargs >/dev/null 2>&1 || die "xargs is not available"

# Use "xargs" to parse quoted args correctly into a "java" command.
printf '%s\n' "$@" | xargs -r java $JVM_OPTS $ADD_OPTS $@