#!/bin/sh

##############################################################################
#
# Gradle start up script for POSIX generated by Gradle.
#
# Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script.
#
#   (2) All environment variables ending with _OPTS are used as additional
#       options for the JVM hosting the Gradle process.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=$(dirname "$app_path")
    [ -h "$app_path" ]
do
    ls=$(ls -ld "$app_path")
    link=$(expr "$ls" : '.*-> \(.*\)$')
    case $link in             #(
      /*)   app_path="$link" ;; #(
      *)    app_path="$APP_HOME$link" ;;
    esac
done

# Change to the directory the script is in
cd "$(dirname "$app_path")" || exit

# Add the Gradle wrapper JAR to the classpath
CLASSPATH="$(dirname "$0")/gradle/wrapper/gradle-wrapper.jar"

# Determine the Java command to use to start the JVM
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD="maximum"

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$(uname)" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
  NONSTOP* )        nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        # In POSIX sh, ulimit -H is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC2039,SC3028
        MAX_FD=$(ulimit -H -n) &&
        # shellcheck disable=SC2039,SC3028
        ulimit -n "$MAX_FD"
        # shellcheck disable=SC2039,SC3028
        if [ $? -ne 0 ]; then
            warn "Could not query the maximum file descriptor limit"
        fi
        ;;
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args of this script
#   * ADD_OPTS
#   * default JVM options
#   * main-klass
#   * -classpath
#   * CLASSPATH
#   * -Dapp.name
#   * -Dapp.home
#   * -Dorg.gradle.appname
#   * -Dorg.gradle.wrapper.distribution
set -- \
        -Dorg.gradle.appname="$APP_BASE_NAME" \
        -Dapp.home="$APP_HOME" \
        -Dapp.name="$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Use "xargs" to parse quoted args correctly into a "java" command.
printf '%s\n' "$*" | xargs -r -- java $JVM_OPTS $ADD_OPTS "$@"